export {
  faShapes,
  faArrowRight,
  faArrowDown,
  faChartLine,
  faLaptopCode,
  faCalendarCheck,
  faRobot,
  faMagnifyingGlassChart,
  faBolt,
  faCheck,
  faStar,
  faQuoteLeft,
  faEnvelope,
  faPhone,
  faLocationDot,
  faPaperPlane,
  faXmark,
  faBars,
  faLeaf,
  faLayerGroup,
  faCalendarDays,
  faMobileScreen,
  faPenRuler,
  faBell,
  faClock,
  faSliders,
  faCar,
  faGear,
  faArrowLeft,
  faShieldHalved,
  faCode,
  faSun,
  faMoon,
} from "@fortawesome/free-solid-svg-icons";

export { faEnvelope as faEnvelopeRegular } from "@fortawesome/free-regular-svg-icons";

export { faGoogle } from "@fortawesome/free-brands-svg-icons";
